Repository maby200/proyecto_u7, pull requests merged in 2023-01, with the labels that each got.

#4 feature: add PR Template
  .github/pull_request_template.md
Labels: feature

#5 feature: add model user and migrate
  prisma/dev.db
  prisma/dev.db-journal
  prisma/migrations/20230119055538_add_model_user/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: feature

#6 feat/add_configuration
  .gitignore
  index.ts
  nodemon.json
  package-lock.json
  package.json
  src/app.ts
  src/index.ts
  tsconfig.json
Labels: feature

#9 feat/modulo-users-login-signup-token
  index.js
  index.ts
  package-lock.json
  package.json
  prisma/dev.db
  prisma/dev.db-journal
  prisma/schema.prisma
  src/app.ts
  src/components/index.ts
  src/components/users/controller.ts
  src/components/users/index.ts
  src/index.ts
  src/router/index.ts
Labels: bug, feature

#10 feat/7-create-module-playlist-and-edit-schema
  .gitignore
  package-lock.json
  package.json
  prisma/dev.db
  prisma/migrations/20230122054911_change_models/migration.sql
  prisma/schema.prisma
  src/app.ts
  src/components/index.ts
  src/components/playlist/controller.ts
  src/components/playlist/index.ts
  src/components/users/controller.ts
  src/datasource/index.ts
  src/index.ts
  src/router/index.ts
Labels: enhancement, feature, fix

#11 created: routes to post and get (all & by Id)
  prisma/dev.db-journal
  src/components/index.ts
  src/components/songs/controller.ts
  src/components/songs/index.ts
  src/router/index.ts
Labels: feature

#13 ENH: middleware al metodo /users/get
  src/components/middleware/index.ts
  src/components/users/index.ts
Labels: enhancement

#14 ENH/7.2-create-route-findId
  prisma/dev.db-journal
  src/components/playlist/controller.ts
  src/components/playlist/index.ts
Labels: enhancement

#15 feat/8.3-addfunction-list_songs-public-and-private
  src/components/songs/controller.ts
  src/components/users/index.ts
Labels: feature

#16 fix_errors_and_add_dotenv
  src/app.ts
  src/components/middleware/index.ts
  src/components/playlist/controller.ts
  src/components/songs/controller.ts
  src/components/users/controller.ts
Labels: enhancement, fix

#17 add_readme_and_env_example
  .env.example
  README.md
Labels: documentation
